SELECT m.ID AS "가게 ID", m.NAME AS NAME, count(e.id) AS "결제 횟수"
FROM  MERCHANTS AS m
JOIN CARD_USAGES AS e ON m.ID = e.MERCHANT_ID
WHERE (m.NAME LIKE '%강남%' OR m.NAME LIKE '%논현%') AND e.CATEGORY = 0
GROUP BY m.ID, m.NAME
ORDER BY m.ID