-- 코드를 입력하세요
SELECT h.OWNER AS OWNER, (ABS(h.X -ca.x) + ABS(h.Y-ca.y)) AS DISTANCE
FROM HOUSE_LOCATIONS AS h, (SELECT x, y FROM HOUSE_LOCATIONS WHERE OWNER = 'Carlos') AS ca
WHERE h.OWNER != 'Carlos'
ORDER BY DISTANCE DESC
LIMIT 1;